services:
  - type: web
    name: adaptnet-climate
    env: python
    buildCommand: pip install -r requirements.txt
    # startCommand: python render_app.py
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
